# Generated by Django 5.0.3 on 2024-03-31 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('blockchain_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('launch_date', models.DateField()),
                ('block_time', models.FloatField(null=True)),
                ('consensus_mechanism', models.CharField(max_length=255)),
                ('smart_contract_support', models.BooleanField()),
                ('fork_date', models.DateField(null=True)),
                ('fork_type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('cryptocurrency_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('launch_date', models.DateField()),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=200)),
                ('registrationdate', models.DateTimeField(max_length=20)),
                ('last_login', models.DateTimeField(max_length=20)),
                ('birthdate', models.DateTimeField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('cryptocurrency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.cryptocurrency')),
                ('price_usd', models.DecimalField(decimal_places=10, max_digits=15)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume_24hr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change_24hr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('all_time_high', models.DecimalField(decimal_places=10, max_digits=15)),
                ('all_time_low', models.DecimalField(decimal_places=10, max_digits=15)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=45)),
                ('wallet_address', models.CharField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=15)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cryptocurrency')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=15)),
                ('transaction_type', models.CharField(default='BUY', max_length=45)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance_total', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('address', models.CharField(max_length=45, unique=True)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='WalletCurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, max_digits=15)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cryptocurrency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wallet')),
            ],
        ),
    ]
