# Generated by Django 5.0.3 on 2024-04-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='walletcurrencies',
            options={'managed': False},
        ),
    ]
