# Generated by Django 5.0.3 on 2024-04-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blockchain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='blockchain',
            table='Blockchain',
        ),
        migrations.AlterModelTable(
            name='cryptocurrency',
            table='Cryptocurrency',
        ),
        migrations.AlterModelTable(
            name='market',
            table='Market',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
        migrations.AlterModelTable(
            name='transfer',
            table='Transfer',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='Wallet',
        ),
        migrations.AlterModelTable(
            name='walletcurrencies',
            table='Wallet_Currencies',
        ),
    ]
